# Default values for flask-kafka-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80



# Global configuration
global:

  namespace: "retrunbuild"

  environment: prod
  
  imageTag: v1.1.0
  
  imagePullSecrets:
    - name: retrunbuild
  
  labels:
    app.kubernetes.io/part-of: retrunbuild-backend



defaults:
  resources:
    limits:
      cpu: "6"
      memory: "8Gi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  hpa:
    enabled: true
    minReplicas: 4
    maxReplicas: 4
    cpuUtilization: 80
    memoryUtilization: 80
  secrets:
    - name: repo-secrets

modules:
  producer:
    enabled: true
    ingress:
      enabled: false
    image:
      repository: repo-producer
      tag: latest
    port: 5000
    replicas: 1

    healthCheck:
      enabled: true
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 120  
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 120
        failureThreshold: 5

  consumer:
    enabled: true
    ingress:
      enabled: false
    image:
      repository: repo-consumer
      tag: latest
    port: 5000
    replicas: 1
    healthCheck:
      enabled: true
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 120  
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 120
        failureThreshold: 5

  zookeeper:
    enabled: true
    ingress:
      enabled: false
    image:
      repository: wurstmeister/zookeeper
      tag: latest
    port: 2181
    replicas: 1


  kafka:
    enabled: true
    ingress:
      enabled: false
    image:
      repository: wurstmeister/kafka:2.13-2.8.1
      tag: latest
    port: 9092
    replicas: 1
    volume:
      enabled: true
      volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-storage
          pvc:
            enabled: true
            claimName: kafka-data
    envs:
      enabled: true
      envs:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"

  akhq:
    enabled: true
    ingress:
      enabled: false
    image:
      repository: tchiotludo/akhq:0.24.0
      tag: latest
    port: 8080
    replicas: 1

    volume:
      enabled: true
      volumeMounts:
        - name: config
          mountPath: /app/application.yml
          subPath: application.yml
      volumes:
        - name: config
          configMap:
            name: akhq-config





volumes:
  - name: kafka-data
    pvc:
      enabled: true
      claimName: kafka-data
      
configmaps:
  - name: akhq-config
    data:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9093"
              zookeeper:
                connect: "zookeeper:2181" 






