{{- range $serviceName, $serviceConfig := .Values.modules }}
{{- if and (eq $serviceConfig.enabled true) ($serviceConfig.image.repository) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  labels:
    {{- include "flask-kafka-apps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flask-kafka-apps.selectorLabels" . | nindent 4 }}

{{- end }}
{{- end }}
